use bdk::prelude::*;

use crate::tables::*;

#[server(endpoint = "/members", input = server_fn::codec::GetUrl)]
pub async fn get_members() -> Result<Vec<Member>, ServerFnError> {
    Ok(
        vec![
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Summer".to_string(),
                role: MemberRole::Founder,
                image: "https://dev.biyard.co/members/summer.png".to_string(),
                description: "Our founder and CEO, Summer is an educator in the Korean Web3 industry, specializing in industry convergence and DAO technology and applications in the context of blockchain and Web3.0. In the UK, she is also a Venture Partner at Simsan Ventures. Simsan Ventures is a London-based venture capital firm focused on early stage and deep tech companies. In addition, she is the CIO of the Korea office of Simsan Ventures.".to_string(),
                email: "summer@biyard.co".to_string(),
                github: None,
                linkedin: Some("https://www.linkedin.com/in/summerhyejinpark/".to_string()),
                web: None,
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Miner".to_string(),
                role: MemberRole::CeoAndCto,
                image: "https://dev.biyard.co/members/miner.png".to_string(),
                description: "Miner obtained his PhD in cryptography and computer security. He has published several SCI(E) papers in the field of security. He led the development of the messenger part of a game platform with 75 million concurrent users, and served as the development leader and a product owner of an EVM-based blockchain cloud platform. In addition, he has contributed various open source activities both private and public blockchains.".to_string(),
                email: "miner@biyard.co".to_string(),
                github: Some("https://github.com/hackartists".to_string()),
                linkedin: Some("https://www.linkedin.com/in/hackartist/".to_string()),
                web: Some("https://www.hackartist.io".to_string()),
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Rosa".to_string(),
                role: MemberRole::PM,
                image: "https://dev.biyard.co/members/rosa.png".to_string(),
                description: "Senior Project Manager with over 10 years of experience in developing and managing projects for major corporations and national research institutes in South Korea. She holds a Bachelor's and Master's degree in Engineering from Korea University, as well as a Master's in Technology Management from KAIST.".to_string(),
                email: "rosa@biyard.co".to_string(),
                github: None,
                linkedin: None,
                web: None,
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Victor".to_string(),
                role: MemberRole::Developer,
                image: "https://dev.biyard.co/members/victor.png".to_string(),
                description: "Victor is a computer science-trained developer specializing in web and mobile frontend development, as well as blockchain smart contract implementation. He leads the development of Incheon Universe, one of Biyard's flagship services.".to_string(),
                email: "victor@biyard.co".to_string(),
                github: Some("https://github.com/victor138128".to_string()),
                linkedin: Some("https://www.linkedin.com/in/victor-lee-606807302".to_string()),
                web: Some("https://blog.naver.com/yepp0517".to_string()),
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Ryan".to_string(),
                role: MemberRole::Developer,
                image: "https://dev.biyard.co/members/ryan.png".to_string(),
                description: "Ryan is a developer who majored in Computer Science and primarily develops smart contracts and web applications that run on the blockchain. He contributes in developing various services at Biyard.".to_string(),
                email: "ryan@biyard.co".to_string(),
                github: Some("https://github.com/RyanCho-0".to_string()),
                linkedin: Some("https://www.linkedin.com/in/ryancho-kr".to_string()),
                web: None,
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Jace".to_string(),
                role: MemberRole::Developer,
                image: "https://dev.biyard.co/members/jace.png".to_string(),
                description: "Jace is responsible for planning and designing Biyard's services, focusing on UX and UI. He leads the planning and operation of the Incheon Universe project and also designed the UX and UI for the d.AGIT service.".to_string(),
                email: "ryan@biyard.co".to_string(),
                github: None,
                linkedin: Some("https://www.linkedin.com/in/jace0615".to_string()),
                web: None,
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Jihwan".to_string(),
                role: MemberRole::Researcher,
                image: "https://dev.biyard.co/members/jihwan.png".to_string(),
                description: "Ji-hwan is responsible for analyzing blockchain market trends and technologies. He also manages the company's investments and partnerships, contributing to strategic growth and collaboration.".to_string(),
                email: "jihwan@biyard.co".to_string(),
                github: None,
                linkedin: None,
                web: None,
            },
            Member {
                id: 1,
                created_at: 0,
                updated_at: 0,
                name: "Henry".to_string(),
                role: MemberRole::Developer,
                image: "https://dev.biyard.co/members/henry.png".to_string(),
                description: "Henry is a full-stack software engineer at Biyard. Currently he is working to solve complex problems with creative and efficient code. It covers various programming languages and technology stacks, and he is especially interested in backend development and system design.".to_string(),
                email: "henry@biyard.co".to_string(),
                github: Some("https://github.com/2miwon".to_string()),
                linkedin: Some("https://www.linkedin.com/in/2miwon".to_string()),
                web: None,
            },
        ]

    )
}
